# Generated by Django 5.2.8 on 2026-03-25 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кейса')),
                ('price', models.IntegerField(verbose_name='цена кейса')),
                ('description', models.TextField(verbose_name='описание кейса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='изображение кейса')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['name'], name='vadim_cases_name_2dfe23_idx'), models.Index(fields=['price'], name='vadim_cases_price_402421_idx')],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название предмета')),
                ('rarity', models.CharField(max_length=50, verbose_name='редкость предмета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена предмета')),
                ('is_stattrack', models.BooleanField(default=False, verbose_name='stattrack')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['name', 'price'],
                'indexes': [models.Index(fields=['name'], name='vadim_items_name_d0fe30_idx'), models.Index(fields=['price'], name='vadim_items_price_a45f16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='почта')),
                ('balance', models.IntegerField(default=0, verbose_name='баланс аккаунта')),
                ('trade_link', models.TextField(blank=True, verbose_name='ссылка для обмена')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('steam_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Steam ID')),
                ('steam_avatar', models.URLField(blank=True, null=True, verbose_name='аватар Steam')),
                ('steam_profile_url', models.URLField(blank=True, null=True, verbose_name='профиль Steam')),
                ('steam_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Steam ник')),
                ('steam_realname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Настоящее имя')),
                ('steam_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('steam_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации Steam')),
                ('last_login_steam', models.DateTimeField(auto_now=True, verbose_name='Последний вход через Steam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма апгрейда')),
                ('upgrade_item', models.CharField(max_length=255, verbose_name='предмет для апгрейда')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предметы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'upgrade',
                'verbose_name_plural': 'upgrades',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма апгрейда')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='шанс выпадения')),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.cases', verbose_name='кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предметы')),
            ],
            options={
                'verbose_name': 'chance',
                'verbose_name_plural': 'chances',
                'ordering': ['item'],
                'indexes': [models.Index(fields=['item'], name='vadim_chanc_item_id_18d5c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['user_name'], name='vadim_users_user_na_6ea3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['steam_id'], name='vadim_users_steam_i_e41133_idx'),
        ),
        migrations.AddIndex(
            model_name='upgrade',
            index=models.Index(fields=['amount'], name='vadim_upgra_amount_a89684_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['name'], name='vadim_contr_name_33c29a_idx'),
        ),
    ]
