# Generated by Django 5.2.7 on 2025-10-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кейса')),
                ('price', models.IntegerField(verbose_name='цена кейса')),
                ('description', models.TextField(verbose_name='описание кейса')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['name'], name='vadim_cases_name_2dfe23_idx'), models.Index(fields=['price'], name='vadim_cases_price_402421_idx')],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название предмета')),
                ('rarity', models.CharField(max_length=50, verbose_name='редкость предмета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена предмета')),
                ('is_stattrack', models.BooleanField(default=False, verbose_name='stattrack')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['name', 'price'],
                'indexes': [models.Index(fields=['name'], name='vadim_items_name_d0fe30_idx'), models.Index(fields=['price'], name='vadim_items_price_a45f16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=255, verbose_name='почта')),
                ('balance', models.IntegerField(default=0, verbose_name='баланс аккаунта')),
                ('trade_link', models.TextField(verbose_name='ссылка для обмена')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['user_name', 'balance'],
                'indexes': [models.Index(fields=['user_name'], name='vadim_users_user_na_6ea3dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='case_contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_chance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='шанс выпадения')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.cases', verbose_name='кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'case_content',
                'verbose_name_plural': 'case_contents',
                'ordering': ['drop_chance'],
                'indexes': [models.Index(fields=['drop_chance'], name='vadim_case__drop_ch_b5959d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма апгрейда')),
                ('upgrade_item', models.CharField(max_length=255, verbose_name='предмет для апгрейда')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предметы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'upgrade',
                'verbose_name_plural': 'upgrades',
                'ordering': ['amount'],
                'indexes': [models.Index(fields=['amount'], name='vadim_upgra_amount_a89684_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма апгрейда')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='vadim_contr_name_33c29a_idx')],
            },
        ),
    ]
