# Generated by Django 5.2.8 on 2026-03-25 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='дата открытия')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.cases', verbose_name='кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='выпавший предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'открытие кейса',
                'verbose_name_plural': 'открытия кейсов',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='vadim.users')),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
