# Generated by Django 5.2.7 on 2025-10-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='шанс выпадения')),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.cases', verbose_name='кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vadim.items', verbose_name='предметы')),
            ],
            options={
                'verbose_name': 'chance',
                'verbose_name_plural': 'chances',
                'ordering': ['item'],
                'indexes': [models.Index(fields=['item'], name='vadim_chanc_item_id_18d5c6_idx')],
            },
        ),
    ]
