# Generated by Django 5.2.8 on 2025-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0002_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='category',
            field=models.CharField(choices=[('popular', 'Популярные'), ('brat', 'Братские')], default='popular', max_length=20, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='cases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='изображение кейса'),
        ),
        migrations.DeleteModel(
            name='case_contents',
        ),
    ]
