# Generated by Django 5.2.8 on 2025-11-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0003_cases_category_cases_image_delete_case_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='category',
        ),
    ]
