# Generated by Django 5.2.8 on 2026-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadim', '0004_remove_cases_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='trade_link',
            field=models.TextField(blank=True, verbose_name='ссылка для обмена'),
        ),
    ]
