# Generated by Django 5.2.6 on 2025-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(verbose_name='имя пользователя')),
                ('email', models.CharField(verbose_name='почта')),
                ('balance', models.IntegerField(verbose_name='баланс аккаунта')),
                ('trade_link', models.TextField(verbose_name='ссылка для обмена')),
                ('role', models.CharField(default='admin', verbose_name='admin or user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['role', 'user_name'],
                'indexes': [models.Index(fields=['user_name'], name='hello_app_u_user_na_7f825e_idx')],
            },
        ),
    ]
