# Generated by Django 5.2.6 on 2025-10-01 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кейса')),
                ('price', models.IntegerField(verbose_name='цена кейса')),
                ('description', models.TextField(verbose_name='описание кейса')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['name'], name='hello_app_c_name_20f9e2_idx'), models.Index(fields=['price'], name='hello_app_c_price_d54b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название предмета')),
                ('rarity', models.CharField(max_length=50, verbose_name='редкость предмета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена предмета')),
                ('is_stattrack', models.BooleanField(default=False, verbose_name='stattrack or no')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['name', 'price'],
                'indexes': [models.Index(fields=['name'], name='hello_app_i_name_4507cc_idx'), models.Index(fields=['price'], name='hello_app_i_price_c5995d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=255, verbose_name='почта')),
                ('balance', models.IntegerField(default=0, verbose_name='баланс аккаунта')),
                ('trade_link', models.TextField(verbose_name='ссылка для обмена')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='admin or user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['user_name', 'balance'],
                'indexes': [models.Index(fields=['user_name'], name='hello_app_u_user_na_7f825e_idx')],
            },
        ),
        migrations.CreateModel(
            name='case_contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_chance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='шанс выпадения')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.cases', verbose_name='кейс')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.items', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'case_content',
                'verbose_name_plural': 'case_contents',
                'ordering': ['drop_chance'],
                'indexes': [models.Index(fields=['drop_chance'], name='hello_app_c_drop_ch_1b894f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма апгрейда')),
                ('upgrade_item', models.CharField(max_length=255, verbose_name='предмет для апгрейда')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.items', verbose_name='предметы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'upgrade',
                'verbose_name_plural': 'upgrades',
                'ordering': ['amount'],
                'indexes': [models.Index(fields=['amount'], name='hello_app_u_amount_d75194_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма апгрейда')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.items', verbose_name='предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_app.users', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hello_app_c_name_abab16_idx')],
            },
        ),
    ]
