# Generated by Django 5.2.6 on 2025-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='desc',
            field=models.CharField(default='No', verbose_name='Умер или нет'),
        ),
    ]
