# Generated by Django 5.2.6 on 2025-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user_name', 'role'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='название предмета')),
                ('image_url', models.CharField(verbose_name='картинка предмета')),
                ('rarity', models.IntegerField(verbose_name='редкость предмета')),
                ('is_stattrack', models.TextField(default='no', verbose_name='stattrack or no')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['name', 'image_url'],
                'indexes': [models.Index(fields=['name'], name='hello_app_i_name_4507cc_idx')],
            },
        ),
    ]
